name: Update Latest Relase

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build VisualNeuro]
    types: 
      - completed

jobs:
  upload_artifact:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master'}}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: 'windows-latest'
            installer: 'visualneuro-installer-win'
          - os: 'macos-latest'
            installer: 'visualneuro-installer-macos'
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Download Windows artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        name: ${{ matrix.installer }}
        workflow: visualneuro.yml

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: VisualNeuro-*
        file_glob: true
        tag: latest
        overwrite: true
        body: "The latest Visual Neuro build, updated for every merged pull request."

    - name: Tag Repo
      uses: richardsimko/update-tag@v1
      with:
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        